parameters:
    pbweb_buzz.client_timeout: 5

services:
    pbweb_buzz.message_factory:
        class: Buzz\Message\Factory\Factory
        public: false

    pbweb_buzz.client:
        class: Buzz\Client\Curl
        public: false
        calls:
            - [setTimeout, ["%pbweb_buzz.client_timeout%"]]
            - [setOption, [10102, ""]] # 10102 = CURLOPT_ENCODING, Enables all supported encodings (gzip!)

    pbweb_buzz.browser:
        class: Buzz\Browser
        arguments:
            - "@pbweb_buzz.client"
            - "@pbweb_buzz.message_factory"
        public: true

    buzz: "@pbweb_buzz.browser"
    Buzz\Browser: "@pbweb_buzz.browser"
